import React from "react";
import { Link } from "react-router-dom";

/* ─── helpers ─── */
function SectionTag({ children, light }) {
  return (
    <div className={`inline-block text-[11px] font-bold tracking-[0.12em] uppercase
      px-3.5 py-1.5 rounded-full mb-4
      ${light ? "bg-white/15 text-brand-100" : "bg-brand-50 text-sky-600"}`}>
      {children}
    </div>
  );
}

export default function About() {
  return (
    <>
      {/* ── HERO ── */}
      <section className="bg-gradient-to-br from-brand-700 to-[#0d2d5e]
        py-20 px-6 md:px-[6%] relative overflow-hidden">
        <div className="absolute bottom-[-70px] right-[-50px] w-80 h-60
          rounded-full bg-sky-400/15" />
        <div className="absolute top-[-40px] left-[-40px] w-56 h-56
          rounded-full bg-brand-600/20" />
        <div className="relative z-10 animate-fade-up anim-fill">
          <SectionTag light>About <img src="/logo-icon.svg" alt="Athenura" className="inline-block h-3 w-auto object-contain -mt-1 mr-1 align-middle" /></SectionTag>
          <h1 className="font-syne font-extrabold text-[clamp(32px,5vw,56px)]
            text-white leading-tight mb-4">
            Code. Create.
            <br />Innovate.
          </h1>
          <p className="text-[15px] text-brand-100 max-w-[480px] leading-7">
            Athenura is an AI-powered quiz contest platform built to make intern
            evaluation smarter, fairer, and fully automated — one domain at a time.
          </p>
        </div>
      </section>

      {/* ── MISSION ── */}
      <section className="py-16 px-6 md:px-[6%]">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center mb-12">

          {/* Text */}
          <div className="animate-fade-up anim-fill delay-1">
            <SectionTag>Our Mission</SectionTag>
            <h2 className="font-syne font-extrabold text-[clamp(22px,3vw,36px)]
              text-sky-900 mb-4 leading-tight">
              Built for the intern generation
            </h2>
            <p className="text-[13px] text-gray-500 leading-relaxed mb-3">
              Athenura was created to remove friction from talent evaluation.
              Instead of one-size-fits-all quizzes, every intern gets questions
              tailored to their exact domain.
            </p>
            <p className="text-[13px] text-gray-500 leading-relaxed mb-3">
              Whether you're Frontend, Data Science, or UI/UX — the platform
              serves the right questions, tracks performance, and celebrates
              wins automatically.
            </p>
            <p className="text-[13px] text-gray-500 leading-relaxed">
              We believe intern evaluation should be automated, transparent,
              and motivating — not manual and arbitrary.
            </p>
          </div>

          {/* Quote card */}
          <div className="bg-gradient-to-br from-sky-50 to-brand-50 rounded-3xl
            p-9 border border-sky-200 relative animate-scale-in anim-fill delay-2">
            <div className="absolute top-4 left-5 font-syne font-extrabold text-[68px]
              text-brand-100 leading-none select-none">"</div>
            <blockquote className="font-syne font-bold text-[17px] text-sky-800
              leading-relaxed mb-4 pt-8">
              "The intern's{" "}
              <span className="text-brand-500">domain</span>{" "}
              decides the quiz automatically — simple for interns, easy to manage for admins."
            </blockquote>
            <cite className="text-xs text-gray-500 not-italic">
              Athenura Platform Design Philosophy
            </cite>
            <ul className="mt-5 flex flex-col gap-2">
              {[
                "Zero manual question writing",
                "Domain-specific evaluation",
                "Transparent leaderboard rankings",
                "Motivation through badges & recognition",
              ].map((item) => (
                <li key={item} className="flex items-center gap-2 text-[13px] text-sky-800">
                  <span className="w-1.5 h-1.5 rounded-full bg-brand-500 flex-shrink-0" />
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Values grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {[
            {
              title: "Automation First",
              desc: "Every quiz is generated by AI. Groq API creates fresh questions instantly and existing ones are reused to avoid duplication.",
            },
            {
              title: "Domain Precision",
              desc: "A Frontend intern never sees a Data Science question. Domain assignment is read from the dataset and enforced at every contest.",
            },
            {
              title: "Merit & Transparency",
              desc: "Rankings are purely score-based with time as tiebreaker. Every intern checks their position via unique ID — no hidden criteria.",
            },
            {
              title: "Recognition Culture",
              desc: "Badges per contest win, Intern of the Month for three wins. History kept forever, monthly counts reset — building long-term motivation.",
            },
          ].map(({ title, desc }) => (
            <div
              key={title}
              className="bg-white border border-sky-100 border-l-[4px] border-l-brand-500
                rounded-2xl p-5 hover:translate-x-1 transition-transform"
            >
              <h3 className="font-syne font-bold text-[14px] text-sky-900 mb-2">{title}</h3>
              <p className="text-[13px] text-gray-500 leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── PLATFORM LAYERS ── */}
      <section className="py-16 px-6 md:px-[6%] bg-sky-50">
        <SectionTag>The Platform</SectionTag>
        <h2 className="font-syne font-extrabold text-[clamp(22px,3vw,36px)]
          text-sky-900 mb-3 leading-tight">
          Three layers, one seamless system
        </h2>
        <p className="text-sm text-gray-500 leading-7 max-w-lg mb-9">
          Athenura is built in three clear layers that work together end to end.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[
            {
              layer: "Layer 1",
              title: "Admin Control",
              desc: "Upload intern data, create contests, trigger AI question generation, and monitor all domain results from one dashboard.",
            },
            {
              layer: "Layer 2",
              title: "Intern Experience",
              desc: "Log in with unique ID and joining date, take the domain quiz, see results instantly, track leaderboard position.",
            },
            {
              layer: "Layer 3",
              title: "Data & Recognition",
              desc: "Scores, time taken, badges, leaderboard ranks, and Intern of the Month — all stored in MongoDB and always accessible.",
            },
          ].map(({ layer, title, desc }) => (
            <div
              key={layer}
              className="bg-white border border-sky-100 rounded-2xl p-6
                hover:-translate-y-1 hover:shadow-[0_14px_36px_rgba(2,132,199,0.1)] transition-all"
            >
              <div className="text-[11px] font-bold uppercase tracking-widest text-sky-500 mb-2">
                {layer}
              </div>
              <h3 className="font-syne font-extrabold text-[17px] text-sky-900 mb-2">{title}</h3>
              <p className="text-[13px] text-gray-500 leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── TECH STACK ── */}
      <section className="py-16 px-6 md:px-[6%]">
        <SectionTag>Technology Stack</SectionTag>
        <h2 className="font-syne font-extrabold text-[clamp(22px,3vw,36px)]
          text-sky-900 mb-9 leading-tight">
          Built on reliable, modern tools
        </h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { name: "MongoDB",  role: "Database & storage"      },
            { name: "Groq API", role: "AI question generation"  },
            { name: "Node.js",  role: "Backend server"          },
            { name: "REST API", role: "All platform endpoints"  },
          ].map(({ name, role }) => (
            <div
              key={name}
              className="text-center py-5 px-4 bg-white border border-sky-100 rounded-2xl
                hover:-translate-y-1 hover:border-sky-300 transition-all"
            >
              <div className="font-syne font-bold text-[14px] text-sky-800">{name}</div>
              <div className="text-xs text-gray-500 mt-1">{role}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="bg-gradient-to-r from-sky-600 to-brand-900
        py-16 px-6 md:px-[6%] text-center relative overflow-hidden">
        <div className="absolute top-[-50px] left-[-50px] w-56 h-56 rounded-full bg-white/[0.06]" />
        <div className="relative z-10">
          <h2 className="font-syne font-extrabold text-[clamp(22px,3.5vw,38px)] text-white mb-3">
            Want to see it in action?
          </h2>
          <p className="text-sky-200 text-sm mb-7 max-w-sm mx-auto leading-7">
            Reach out and we'll walk you through a live demo of the full platform.
          </p>
          <Link
            to="/contact"
            className="inline-block bg-white text-brand-700 px-8 py-3.5 rounded-full
              font-semibold text-sm shadow-[0_6px_20px_rgba(0,0,0,0.15)]
              hover:-translate-y-0.5 transition-all"
          >
            Get in Touch
          </Link>
        </div>
      </section>
    </>
  );
}
